//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 03:02:25 PM CDT 
//


package com.cobrar.banco;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cobrar.banco package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cobrar.banco
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReembolsoResponse }
     * 
     */
    public ReembolsoResponse createReembolsoResponse() {
        return new ReembolsoResponse();
    }

    /**
     * Create an instance of {@link CobrarResponse }
     * 
     */
    public CobrarResponse createCobrarResponse() {
        return new CobrarResponse();
    }

    /**
     * Create an instance of {@link ReembolsoRequest }
     * 
     */
    public ReembolsoRequest createReembolsoRequest() {
        return new ReembolsoRequest();
    }

    /**
     * Create an instance of {@link CobrarRequest }
     * 
     */
    public CobrarRequest createCobrarRequest() {
        return new CobrarRequest();
    }

}
