//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 03:02:25 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cobrar.com/Banco", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cobrar.banco;
